### ISSUE TITLE
Remove ESLint from the project

### ISSUE THREAD

**Issue by celeroncoder** [AgencySynapse/synapse#20]
ESLint is enforcing some useless rules that will only get in the way when developing and building the project. Hence, it better to remove it. The current deployment is also failing because of some `eslint` rules:

![image](https://github.com/AgencySynapse/synapse/assets/76873719/59167769-6a64-4828-b1cd-86dc3695ab44)

---

Remove the following things:
- [x] `eslint` config,
- [x] the `lint` script form `package.json`,
- [x] remove any `eslint` related package

**Comment by coderKrysio** [comment]
fixed `eslint` bugs in pr #39
